/**
 * pdfGenerator.js
 * Generates professional PDFs for freight documents:
 *  - Bill of Lading (BOL)
 *  - Rate Confirmation
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const UPLOADS_DIR = path.join(__dirname, '../public/documents/uploads');
if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });

// ── Shared helpers ──────────────────────────────────────────────────────────

function drawHRule(doc, y, color) {
  doc.moveTo(50, y).lineTo(562, y).strokeColor(color || '#334155').lineWidth(0.5).stroke();
}

function fmtDate(d) {
  if (!d) return 'N/A';
  return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function fmtMoney(n) {
  return '$' + Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function addHeader(doc, title, subtitle) {
  doc.rect(0, 0, 612, 90).fill('#1e1040');
  doc.fontSize(22).fillColor('#ffffff').font('Helvetica-Bold')
    .text('FreightConnect', 50, 22);
  doc.fontSize(10).fillColor('#a78bfa').font('Helvetica')
    .text('www.freightconnect.io', 50, 48);
  doc.fontSize(18).fillColor('#ffffff').font('Helvetica-Bold')
    .text(title, 300, 22, { align: 'right', width: 262 });
  if (subtitle) {
    doc.fontSize(10).fillColor('#a78bfa').font('Helvetica')
      .text(subtitle, 300, 48, { align: 'right', width: 262 });
  }
  doc.fillColor('#000000');
}

function addFooter(doc) {
  const y = doc.page.height - 50;
  drawHRule(doc, y - 10, '#e2e8f0');
  doc.fontSize(9).fillColor('#64748b')
    .text(
      'Generated by FreightConnect · ' + new Date().toLocaleDateString(),
      50, y, { align: 'center', width: 512 }
    );
}

function sectionTitle(doc, text, y) {
  doc.rect(50, y, 512, 20).fill('#f1f5f9');
  doc.fontSize(10).fillColor('#1e1040').font('Helvetica-Bold')
    .text(text, 56, y + 5);
  doc.font('Helvetica').fillColor('#000000');
  return y + 28;
}

function infoRow(doc, label, value, y) {
  doc.fontSize(9.5).fillColor('#64748b').font('Helvetica')
    .text(label, 50, y, { width: 180 });
  doc.fontSize(9.5).fillColor('#1e293b').font('Helvetica-Bold')
    .text(String(value != null ? value : 'N/A'), 240, y, { width: 322 });
  return y + 17;
}

function sigLine(doc, label, x, y, lineWidth) {
  doc.fontSize(9).fillColor('#1e293b').font('Helvetica').text(label, x, y + 4);
  doc.moveTo(x + 110, y + 18).lineTo(x + lineWidth, y + 18)
    .strokeColor('#94a3b8').lineWidth(0.8).stroke();
}

// ── Bill of Lading ───────────────────────────────────────────────────────────

exports.generateBOL = (load, carrier, shipper) => {
  return new Promise((resolve, reject) => {
    const fileName = load._id + '-bol.pdf';
    const filePath = path.join(UPLOADS_DIR, fileName);

    const doc = new PDFDocument({ size: 'LETTER', margins: { top: 100, bottom: 60, left: 50, right: 50 } });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    addHeader(doc, 'BILL OF LADING', 'BOL #' + String(load._id).slice(-8).toUpperCase());

    let y = 110;

    // Parties
    y = sectionTitle(doc, 'PARTIES', y);
    y = infoRow(doc, 'Shipper (Company)', (shipper && (shipper.companyName || shipper.name)) || 'N/A', y);
    y = infoRow(doc, 'Shipper Email', (shipper && shipper.email) || 'N/A', y);
    y = infoRow(doc, 'Carrier (Company)', (carrier && (carrier.companyName || carrier.name)) || 'N/A', y);
    y = infoRow(doc, 'Carrier Email', (carrier && carrier.email) || 'N/A', y);
    y = infoRow(doc, 'MC Number', (carrier && (carrier.mcNumber || (carrier.verification && carrier.verification.mcNumber))) || 'N/A', y);
    y = infoRow(doc, 'DOT Number', (carrier && (carrier.dotNumber || (carrier.verification && carrier.verification.dotNumber))) || 'N/A', y);
    y += 8; drawHRule(doc, y); y += 12;

    // Shipment Details
    y = sectionTitle(doc, 'SHIPMENT DETAILS', y);
    y = infoRow(doc, 'Load ID', String(load._id), y);
    y = infoRow(doc, 'Title / Description', load.title, y);
    y = infoRow(doc, 'Origin', load.origin, y);
    y = infoRow(doc, 'Destination', load.destination, y);
    y = infoRow(doc, 'Equipment Type', load.equipmentType, y);
    y = infoRow(doc, 'Commodity', load.commodityType || 'General Freight', y);
    if (load.loadWeight) y = infoRow(doc, 'Weight (lbs)', load.loadWeight.toLocaleString(), y);
    if (load.loadDimensions && load.loadDimensions.length) {
      const d = load.loadDimensions;
      y = infoRow(doc, 'Dimensions', d.length + 'L × ' + d.width + 'W × ' + d.height + 'H ft', y);
    }
    y = infoRow(doc, 'Hazardous Material', load.hazardousMaterial ? 'YES — See special instructions' : 'No', y);
    if (load.specialInstructions) y = infoRow(doc, 'Special Instructions', load.specialInstructions, y);
    y += 8; drawHRule(doc, y); y += 12;

    // Dates & Rate
    y = sectionTitle(doc, 'DATES & RATE', y);
    y = infoRow(doc, 'Pickup Window Start', fmtDate(load.pickupTimeWindow && load.pickupTimeWindow.start), y);
    y = infoRow(doc, 'Pickup Window End', fmtDate(load.pickupTimeWindow && load.pickupTimeWindow.end), y);
    y = infoRow(doc, 'Delivery Window Start', fmtDate(load.deliveryTimeWindow && load.deliveryTimeWindow.start), y);
    y = infoRow(doc, 'Delivery Window End', fmtDate(load.deliveryTimeWindow && load.deliveryTimeWindow.end), y);
    y = infoRow(doc, 'Delivered At', fmtDate(load.deliveredAt), y);
    y = infoRow(doc, 'Agreed Rate', fmtMoney(load.rate), y);
    y += 8; drawHRule(doc, y); y += 16;

    // Terms
    doc.fontSize(8.5).fillColor('#64748b')
      .text(
        'This Bill of Lading is issued pursuant to the terms and conditions agreed upon by shipper and carrier. ' +
        'The carrier acknowledges receipt of the shipment in apparent good order. The carrier is responsible for ' +
        'the safe and timely delivery of cargo as described above. Disputes subject to applicable freight law.',
        50, y, { width: 512, lineGap: 3 }
      );
    y += 50;

    // Signatures
    y = sectionTitle(doc, 'SIGNATURES', y);
    sigLine(doc, 'Carrier Signature:', 50, y, 300);
    sigLine(doc, 'Shipper Signature:', 320, y, 562);
    sigLine(doc, 'Print Name:', 50, y + 28, 300);
    sigLine(doc, 'Print Name:', 320, y + 28, 562);
    sigLine(doc, 'Date:', 50, y + 56, 300);
    sigLine(doc, 'Date:', 320, y + 56, 562);

    addFooter(doc);
    doc.end();
    stream.on('finish', () => resolve('/documents/uploads/' + fileName));
    stream.on('error', reject);
  });
};

// ── Rate Confirmation ────────────────────────────────────────────────────────

exports.generateRateConfirmation = (load, carrier, shipper) => {
  return new Promise((resolve, reject) => {
    const fileName = load._id + '-ratecon.pdf';
    const filePath = path.join(UPLOADS_DIR, fileName);

    const doc = new PDFDocument({ size: 'LETTER', margins: { top: 100, bottom: 60, left: 50, right: 50 } });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    addHeader(doc, 'RATE CONFIRMATION', 'RC #' + String(load._id).slice(-8).toUpperCase());

    let y = 110;

    // Parties
    y = sectionTitle(doc, 'PARTIES', y);
    y = infoRow(doc, 'Broker / Shipper', (shipper && (shipper.companyName || shipper.name)) || 'N/A', y);
    y = infoRow(doc, 'Shipper Contact', (shipper && shipper.email) || 'N/A', y);
    y = infoRow(doc, 'Carrier', (carrier && (carrier.companyName || carrier.name)) || 'N/A', y);
    y = infoRow(doc, 'Carrier Contact', (carrier && carrier.email) || 'N/A', y);
    y = infoRow(doc, 'MC Number', (carrier && (carrier.mcNumber || (carrier.verification && carrier.verification.mcNumber))) || 'N/A', y);
    y = infoRow(doc, 'DOT Number', (carrier && (carrier.dotNumber || (carrier.verification && carrier.verification.dotNumber))) || 'N/A', y);
    y += 8; drawHRule(doc, y); y += 12;

    // Load Details
    y = sectionTitle(doc, 'LOAD DETAILS', y);
    y = infoRow(doc, 'Load Reference', String(load._id), y);
    y = infoRow(doc, 'Description', load.title, y);
    y = infoRow(doc, 'Origin', load.origin, y);
    y = infoRow(doc, 'Destination', load.destination, y);
    y = infoRow(doc, 'Equipment Type', load.equipmentType, y);
    y = infoRow(doc, 'Commodity', load.commodityType || 'General Freight', y);
    if (load.loadWeight) y = infoRow(doc, 'Weight', load.loadWeight.toLocaleString() + ' lbs', y);
    y = infoRow(doc, 'Hazardous Material', load.hazardousMaterial ? 'YES' : 'No', y);
    y += 8; drawHRule(doc, y); y += 12;

    // Schedule
    y = sectionTitle(doc, 'PICKUP & DELIVERY SCHEDULE', y);
    y = infoRow(doc, 'Pickup Start', fmtDate(load.pickupTimeWindow && load.pickupTimeWindow.start), y);
    y = infoRow(doc, 'Pickup End', fmtDate(load.pickupTimeWindow && load.pickupTimeWindow.end), y);
    y = infoRow(doc, 'Delivery Start', fmtDate(load.deliveryTimeWindow && load.deliveryTimeWindow.start), y);
    y = infoRow(doc, 'Delivery End', fmtDate(load.deliveryTimeWindow && load.deliveryTimeWindow.end), y);
    if (load.specialInstructions) y = infoRow(doc, 'Special Instructions', load.specialInstructions, y);
    y += 8; drawHRule(doc, y); y += 12;

    // Rate box
    y = sectionTitle(doc, 'RATE & PAYMENT TERMS', y);
    doc.rect(50, y, 512, 36).fillAndStroke('#f0fdf4', '#16a34a');
    doc.fontSize(13).fillColor('#15803d').font('Helvetica-Bold')
      .text('Total Agreed Rate:', 66, y + 10);
    doc.fontSize(16).fillColor('#166534')
      .text(fmtMoney(load.rate), 350, y + 7, { align: 'right', width: 200 });
    doc.font('Helvetica').fillColor('#000000');
    y += 48;
    y = infoRow(doc, 'Payment Terms', 'Net 30 days from delivery and receipt of invoice', y);
    y = infoRow(doc, 'Payment Method', 'ACH / Wire (via FreightConnect escrow)', y);
    y += 8; drawHRule(doc, y); y += 12;

    // Terms
    y = sectionTitle(doc, 'TERMS & CONDITIONS', y);
    doc.fontSize(8.5).fillColor('#64748b').font('Helvetica')
      .text(
        '1. Carrier agrees to transport the described freight from origin to destination at the agreed rate.\n' +
        '2. Carrier shall comply with all applicable federal and state regulations.\n' +
        '3. Payment will be released from escrow upon delivery confirmation and signed BOL receipt.\n' +
        '4. Any claims for loss or damage must be filed within 9 months of delivery.\n' +
        '5. This rate confirmation, once signed by both parties, constitutes a binding agreement.',
        50, y, { width: 512, lineGap: 4 }
      );
    y += 90;

    // Signatures
    if (y > doc.page.height - 180) { doc.addPage(); y = 60; }
    y = sectionTitle(doc, 'ACCEPTANCE SIGNATURES', y);
    sigLine(doc, 'Carrier Acceptance:', 50, y, 300);
    sigLine(doc, 'Shipper Acceptance:', 320, y, 562);
    sigLine(doc, 'Print Name:', 50, y + 28, 300);
    sigLine(doc, 'Print Name:', 320, y + 28, 562);
    sigLine(doc, 'Date:', 50, y + 56, 300);
    sigLine(doc, 'Date:', 320, y + 56, 562);

    addFooter(doc);
    doc.end();
    stream.on('finish', () => resolve('/documents/uploads/' + fileName));
    stream.on('error', reject);
  });
};
