/**
 * ELDLog — Electronic Logging Device / Hours of Service
 *
 * Tracks driver duty status changes and daily HOS summaries.
 * Federal regulations (simplified):
 *   - 11-hour driving limit per day
 *   - 14-hour on-duty window per day
 *   - 10 consecutive hours off before driving again
 *   - 70-hour limit over 8 rolling days
 *   - 30-minute break required after 8 hours driving
 */

const mongoose = require('mongoose');

const DUTY_STATUSES = ['OFF_DUTY', 'SLEEPER_BERTH', 'DRIVING', 'ON_DUTY_NOT_DRIVING'];

const StatusEventSchema = new mongoose.Schema({
  status:     { type: String, enum: DUTY_STATUSES, required: true },
  startTime:  { type: Date, required: true },
  endTime:    Date,               // null = currently active
  durationMinutes: Number,        // computed on endTime set
  location:   String,
  load:       { type: mongoose.Schema.Types.ObjectId, ref: 'Load', default: null },
  odometer:   Number,
  notes:      String,
  autoGenerated: { type: Boolean, default: false },
}, { _id: true });

const ViolationSchema = new mongoose.Schema({
  type:      { type: String },  // e.g. '11_HOUR', '14_HOUR', '70_HOUR', '30_MIN_BREAK'
  message:   String,
  detectedAt: { type: Date, default: Date.now },
  severity:  { type: String, enum: ['warning', 'violation'], default: 'warning' },
}, { _id: false });

const ELDLogSchema = new mongoose.Schema({
  carrier:  { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  date:     { type: String, required: true, index: true }, // YYYY-MM-DD

  // Current status (only meaningful on today's log)
  currentStatus: { type: String, enum: DUTY_STATUSES, default: 'OFF_DUTY' },

  // All status events for this day
  events: [StatusEventSchema],

  // Daily totals (minutes)
  totals: {
    drivingMinutes:         { type: Number, default: 0 },
    onDutyNotDrivingMinutes:{ type: Number, default: 0 },
    sleeperMinutes:         { type: Number, default: 0 },
    offDutyMinutes:         { type: Number, default: 0 },
  },

  // HOS remaining (minutes) — recomputed on each status change
  remaining: {
    driveMinutes:    { type: Number, default: 660 },  // 11h = 660min
    onDutyMinutes:   { type: Number, default: 840 },  // 14h = 840min
    cycleMinutes:    { type: Number, default: 4200 },  // 70h = 4200min
    breakDueIn:      { type: Number, default: 480 },  // 8h = 480min until break required
  },

  violations: [ViolationSchema],

  certified: { type: Boolean, default: false },
  certifiedAt: Date,

  // Starting odometer for this day
  startOdometer: Number,
  endOdometer:   Number,
}, { timestamps: true });

ELDLogSchema.index({ carrier: 1, date: -1 }, { unique: true });

module.exports = mongoose.model('ELDLog', ELDLogSchema);
